name: Building Image and push GHCR

on: [push]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Berikan izin untuk menulis paket (image)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Ambil kode dari repositori

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Menggunakan username GitHub
          password: ${{ secrets.GITHUB_TOKEN }} # Menggunakan GITHUB_TOKEN bawaan

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Direktori tempat Dockerfile berada
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          buildArgs: VITE_HOST=http://api # Nama image dengan tag unik
          